#this is context properties
#Tue Feb 10 10:59:37 CET 2026
Context_Postgres1_AdditionalParams=
Context_Postgres1_Database=postgres
Context_Postgres1_Login=lerba
Context_Postgres1_Password=enc\:routine.encryption.key.v1\:gR8qAlfPsz1EyeP9alXjeAHZw7oE9eILmFvauIWvdplSQh4\=
Context_Postgres1_Port=5432
Context_Postgres1_Schema=lerba
Context_Postgres1_Server=10.3.0.120
parametro_input=Lorenzo
