#this is context properties
#Tue Feb 10 10:48:08 CET 2026
Context_Postgres1_Schema=lerba
Context_Postgres1_Login=lerba
Context_Postgres1_Port=5432
Context_Postgres1_Password=enc\:routine.encryption.key.v1\:WbHgowCGTht2dRdbng8WzOFt6LGYoHz2O0my2IdN1IMGqtU\=
Context_Postgres1_Server=10.3.0.120
Context_Postgres1_Database=postgres
Context_Postgres1_AdditionalParams=
