#this is context properties
#Tue Feb 10 10:25:46 CET 2026
Context_Postgres1_Schema=lerba
Context_Postgres1_Login=lerba
Context_Postgres1_Port=5432
Context_Postgres1_Password=enc\:routine.encryption.key.v1\:xnx57f/7FV91/5jA7Nm3EHqZCymMNhrhawIwaUrJwGdcq5w\=
Context_Postgres1_Server=10.3.0.120
Context_Postgres1_Database=postgres
Context_Postgres1_AdditionalParams=
